# Erstellen einer Matrix

Wir haben bereits Vektoren behandelt, die es uns erlauben indexierte Elemente zu speichern. Eine Matrix erlaubt es uns darüberhinaus zweidimensionale Datenststruckturen von Elementen des selben Datentyps zu erstellen.

Bevor wir jetzt mit den Matrizen beginnen sollten wir uns noch einen kleinen Tipp zur Erstellung von sequenziellen Zahlenfolgen anschauen. Wir können die *Doppelpunkt-Notation* verwenden, die wir vom Slicing kennen, um sequentielle Vektoren zu erstellen:

In [1]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

Toll! Um jetzt eine Matrix in R zu erstellen nutzen wir die `matrix()` Funktion. Wir können einen Vektor übergeben:

In [3]:
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

Ist dir aufgefallen, wie der Output angezeigt wird? Wir haben eine zweidimensionale Matrix mit 10 Zeilen und einer Spalte erhalten. Was passiert, wenn wir die Anzahl an Zeilen festlegen wollen? Wir übergeben das `nrow` Argument:

In [4]:
matrix(v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

Wir haben jetzt also eine 2 mal 5 Matrix. Dies konnten wir durch das `nrow` Argument erzeugen. Wie legen wir nun die Reihenfolge der Elemente fest? Wir könnten zuerst die Spalten füllen (wie es im Beispiel gerade eben passiert ist) oder zuerst die Zeilen. Das `byrow` Argument ermögliocht es uns, dies festzulegen. Hier zwei Beispiele:

In [5]:
matrix(1:12,byrow = FALSE,nrow=4)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [6]:
matrix(1:12, byrow=TRUE, nrow=4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [7]:
v

[1]  1  2  3  4  5  6  7  8  9 10

## Matrizen aus Vektoren erstellen

Wir können mehrere Vektoren kombinieren, um sie in eine Matrix einzuspielen. Stell dir beispielhaft die beiden folgenden Vektoren von Aktienpreisen vor:

In [8]:
# Keine echten Preise
goog <- c(450,451,452,445,468)
msft <- c(230,231,232,236,228)

In [9]:
aktien <- c(goog,msft)

In [10]:
aktien.matrix <- matrix(aktien,byrow=TRUE,nrow=2)

In [11]:
aktien.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 450  451  452  445  468 
[2,] 230  231  232  236  228

## Matrizen benennen

Jetzt wo wir unsere Matrix erstelt haben ist es naheliegend die Zeilen und Spalten für einen besseren Zugriff zu benennen. Das funktioniert prinzipiell gleich wie die `names()` Funktion für Vektoren: Wir definieren `colnames()` (für die Spalten) und `rownames()` (für die Zeilen). Bennenen wir nun unsere Aktien-Matrix:

In [12]:
tage <- c('Mo','Di','Mi','Do','Fr')
aktien.namen <- c('GOOG','MSFT')

In [13]:
colnames(aktien.matrix) <- tage
rownames(aktien.matrix) <- aktien.namen

In [14]:
aktien.matrix

Mo  Di  Mi  Do  Fr 
GOOG 450 451 452 445 468
MSFT 230 231 232 236 228

Sieht gut aus! Wir bauen uns so langsam etwas wirklich funktionelles auf. So langsam erinnert uns das an eine Tabelle.

Das waren die Grundlagen zur Erstellung von Matrizen. In der nächsten Lektion werden wir eine Matrix von Aktienkursen erstellen, behaltet den Code also für spätere Verweise.