# Matrix Auswahl und Indexierung

Genau wie mit Vektoren werden wir die eckigen Klammern nutzen, um Elemente aus einer Matrix auszuwählen. Da wir zwei Dimensionen haben werden wir ein Komma nutzen, um unsere Indexierung für jede Dimension anzugeben.

Die Syntax lautet also

    beispiel.matrix[zeilen,spalten]
    
wobei die Index Notation (z.B. 1:5) als `zeilen` oder `spalten` eingesetzt wird. Sofern eines der beiden (also `zeilen` oder `spalten` leer gelassen wird, werden alle Zeilen bzw. Spalten ausgewählt.

Schauen wir uns einige Beispiele an:

In [1]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)

In [2]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [3]:
# Erste Zeile
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
# Erste Spalte
mat[,1]

[1]  1 11 21 31 41

In [5]:
# Erste drei Zeilen
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [6]:
# Das Rechteck oben rechts auswählen:
# 1,2,3
# 11,12,13

mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [7]:
# Die letzten beiden Spalten
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [8]:
# Das Quadrat in der Mitte auswählen
# 15,16
# 25,26

mat[2:3,5:6]

[,1] [,2]
[1,] 15   16  
[2,] 25   26

Gut gemacht! Die Auswahl und Indexierung ist etwas, dass ihr wirklich üben und verinnerlichen solltet. Versucht einfach ganz bestimmte Teile der Matrix auszuwählen und indexiert sie. Als nächstes lernen wir mehr über die Matrix Arithmetik!