# R Matrizen Übung - Lösung

Im Verlauf dieser Übung werden wir die Datenstruktur "Matrix" wiederholen. Als kleinen Bonus wird es außerdem etwas zum selbst entdecken geben.

**Erstelle 2 Vektoren A und B. A soll die Werte (1,2,3) beinhalten und B die Werte (4,5,6). Mit diesen Vektoren verwende entweder `cbind()` oder `rbind()`, um eine Matrix im Format 2 mal 3 zu erstellen. Nur eine der Verknüpfungsfunktionen ist hier richtig!**

In [1]:
A <- c(1,2,3)
B <- c(4,5,6)
rbind(A,B)

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

**Erstelle eine 3 mal 3 Matrix, die die Zahlen 1 bis 9 beinhaltet. Diese Matrix soll durch das Kürzel 1:9 erstellt werden und durch Definition des nrow Parameters in der matrix() Funktion. Weise diese Matrix der Varaiblen *mat* zu.**

In [2]:
mat <- matrix(1:9,byrow=TRUE,nrow = 3)

**Überprüfe, ob *mat* wirklich eine Matrix ist. Tipp: is.matrix() **

In [3]:
is.matrix(mat)

[1] TRUE

** Erstelle eine 5 mal 5 Matrix, die die Zahlen 1 bis 25 enthält. Diese soll den Namen *mat2* haben. Die oberste Zeile soll außerdem die Werte 1 bis 5 beinhalten.**

In [4]:
mat2 <- matrix(1:25,byrow = TRUE,nrow = 5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

** Nutze die Index Notation, um einen Ausschnitt von *mat2* auszuwählen. Dieser soll wie folgt aussehen:**

    [7,8]
    [12,13]

In [5]:
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

** Nutze die Index Notation, um einen Ausschnitt von *mat2* auszuwählen. Dieser soll wie folgt aussehen:**

    [19,20]
    [24,25]

In [6]:
mat2[4:5,4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

**Wie lautet die Summe aller Elemente in *mat2*?**

In [7]:
sum(mat2)

[1] 325

** Ok, Zeit für unsere letzte Aufgabe! Finde heraus, wie man `runif()` nutzt, um eine 4 mal 5 Matrix zu erstellen, die aus 20 zufällig ausgewählten Zahlen besteht.**

In [8]:
zufmat <- matrix(runif(20,min=0,max=100),nrow = 4)
zufmat

[,1]     [,2]     [,3]     [,4]     [,5]    
[1,] 58.77551 55.38183 29.35536 72.36309 25.23232
[2,] 67.73795 51.91667 23.33315 40.97063 18.66102
[3,] 43.77001 35.92478 41.08313 75.19955 77.06942
[4,] 62.63423 93.69656 79.30356 66.39926 63.25485

In [9]:
# help(runif)

# Gut gemacht!